apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-ops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/volodymyrmedvetskyi/minikube.git
    targetRevision: main
    path: minikube/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true