# ServiceAccount for vmagent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmagent-sa
  namespace: default
---
# ClusterRole for vmagent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-role
rules:
  - apiGroups: [""]
    resources: ["nodes","nodes/proxy","nodes/metrics","endpoints","pods","services"]
    verbs: ["get","list","watch"]
---
# ClusterRoleBinding for vmagent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-role
subjects:
  - kind: ServiceAccount
    name: vmagent-sa
    namespace: default
---
# vmagent configuration Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      serviceAccountName: vmagent-sa
      containers:
        - name: vmagent-container
          image: victoriametrics/vmagent:latest
          ports:
            - containerPort: 8429
          args:
            - -promscrape.config=/etc/vmagent/prometheus.yml
            - -remoteWrite.url=http://victoria-service:8428/api/v1/write
          volumeMounts:
            - name: scrape-config
              mountPath: /etc/vmagent
      volumes:
        - name: scrape-config
          configMap:
            name: vmagent-config
---
# Configuration of vmagent (scrape config)
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'application'
        static_configs:
          - targets: ['application-service:3000']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['ksm-service:8080']
    
      - job_name: 'kubelet'
        scheme: https
        kubernetes_sd_configs:
          - role: node
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
---
# vmagent configuration Service
apiVersion: v1
kind: Service
metadata:
  name: vmagent-service
spec:
  selector:
    app: vmagent
  ports:
    - protocol: TCP
      port: 8429
      targetPort: 8429
  type: ClusterIP